In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("Documents/house-prices-advanced-regression-techniques/train.csv")

In [4]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [5]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...   
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [6]:
df.shape

(1460, 81)

In [ ]:
for column in df.columns:
    if df[column].dtype == "object":
        df[column].fillna(df[column].mode()[0], inplace=True)
    else:
        df[column].fillna(df[column].median(), inplace=True)

In [15]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [17]:
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype == "object":
        df[column] = le.fit_transform(df[column])

In [25]:
X=df.drop(['SalePrice', 'Id'], axis=1)
Y=df['SalePrice']

In [26]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X)

In [28]:
Test=pd.read_csv("Documents/house-prices-advanced-regression-techniques/test.csv")

In [ ]:
for column in Test.columns:
    if Test[column].dtype == "object":
        Test[column].fillna(Test[column].mode()[0], inplace=True)
    else:
        Test[column].fillna(Test[column].median(), inplace=True)

In [31]:
for column in Test.columns:
    if Test[column].dtype == "object":
        Test[column] = le.fit_transform(Test[column])

In [39]:
#Test=Test.drop(['Id'],axis=1)
test_scaled = scaler.fit_transform(Test)

In [52]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled,Y)
y_pred_rf = rf_model.predict(test_scaled)

In [41]:
y_pred_rf

array([129443.01, 156868.5 , 183726.  , ..., 154992.5 , 114379.78,
       234972.98])

In [53]:
data = pd.DataFrame(y_pred_rf, columns=['Values'])
data.to_excel('submission1.xlsx', index=False, engine='openpyxl')

In [45]:
xgb_model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, random_state=42)
xgb_model.fit(X_train_scaled, Y)
y_pred_xgb = xgb_model.predict(test_scaled)

In [54]:
data = pd.DataFrame(y_pred_xgb, columns=['Values'])
data.to_excel('submission2.xlsx', index=False, engine='openpyxl')

In [48]:
y_pred_xgb

array([126515.75, 156770.9 , 184777.92, ..., 161087.16, 110287.62,
       185525.86], dtype=float32)

In [ ]:
lgb_model = LGBMRegressor(n_estimators=100, random_state=42)
lgb_model.fit(X_train_scaled,Y)
y_pred_lgb = lgb_model.predict(test_scaled)

In [50]:
y_pred_lgb

array([128700.90162106, 155381.28509266, 180659.10578167, ...,
       182759.35397445, 118304.43046746, 221782.56693322])

In [55]:
data = pd.DataFrame(y_pred_lgb, columns=['Values'])
data.to_excel('submission3.xlsx', index=False, engine='openpyxl')